#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.2.{build}                 # You can use {branch} to, for example

# branches to build
branches:
  only:
    - master
    - dev

# Do not build on tags (GitHub only)
skip_tags: true

# fetch repository as zip archive
shallow_clone: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012 R2

# environment variables
environment:
  github_oauth_token:
    secure: jqtdWF2szgieS3RJDDjtE6Ttj0QXORa+kmLJkHCCBpKsyMz/UeFOZSfIP2jHu9L2

# this is how to allow failing jobs in the matrix
matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

build:
  parallel: true           # enable MSBuild parallel builds
  project: CodeEmbed.sln   # path to Visual Studio solution or project

  publish_wap: true        # package Web Application Projects (WAP) for Web Deploy

  # MSBuild verbosity level
  verbosity: minimal

# scripts to run before build
before_build:
  - ps: .\beforeBuild.ps1

# scripts to run after build
after_build:
  - msbuild.exe CodeEmbed.Web.Api\CodeEmbed.Web.Api.csproj @publish.rsp /p:OutputPath="bin" /p:PublishUrl="..\Publish\CodeEmbed.Web.Api"
  - msbuild.exe CodeEmbed.Web.Site\CodeEmbed.Web.Site.csproj @publish.rsp /p:OutputPath="bin" /p:PublishUrl="..\Publish\CodeEmbed.Web.Site"

#---------------------------------#
#       tests configuration       #
#---------------------------------#

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: Publish

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# to run your custom scripts instead of provider deployments
